version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 main.py
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: echo jmir-`date "+%Y-%m-%d-%H"`
        
       



workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build