version: 2.1
orbs: 
  slack: circleci/slack@4.6.1
jobs:

  runner_build_test:
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - slack/notify:
          event: pass
          template: basic_fail_1
      - checkout
      - run:
          name: Run Unit Tests
          command: |
            ls; echo "rootuser"
      - store_artifacts:
          path: test-results

workflows:
  build_test_deploy:
    jobs:
      - runner_build_test