version: 2.1

jobs:

  runner_build_test:
    machine: true
    resource_class: shubhankit/my-resource-class
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: |
            sudo su; ls; echo "rootuser"
      - store_artifacts:
          path: test-results

workflows:
  build_test_deploy:
    jobs:
      - runner_build_test